### ISSUE TITLE
Update openApi to v4 

### ISSUE THREAD

**Issue by jaumard** [jimschubert/intellij-openapi-generator#24]
I need languages only available in v4 (dart2 and jaguar) 

Thanks :)

**Comment by jimschubert** [comment]
@jaumard I've published version 3.0.0 of the intellij plugin, which consumes openapi-generator 4.0.0.

I'd been working to get 3.3.4 consumed, but I was having issues with it. 4.0.0 pulled in cleanly, though.

It can take sometimes up to 48 hours for the Jetbrains Plugin repository to approve and publish changes. If you don't see this released in a couple days, please reopen the issue and I'll look into it.
